### ISSUE TITLE
Issues on the website route: /developer.openpayments.io/applications/

### ISSUE THREAD

**Issue by Christofferos** [openpaymentseurope/docs#28]
1. Connected API products - There are dead links to AIS, PIS and ASPSP.
2. Redirected URI - It is not possible to change the URI from for instance https://docs.google.com/ to https://google.com/
3. Creating a new Application - last section called "Choose API product" has a bug where if you deselect two of the services the ASPSP service gets deselected which is required, but is disabled to interact with.

**Comment by henrikwidlund** [comment]
Late close, but those errors belongs to a different (private) repo.
