### ISSUE TITLE
There are references to sandbox data (PSU Ids) from ESSESESS in multiple files (ASPSP specific documentation for example). This should be removed from the documentation for other ASPSPs and clarified that it is specific to a certain ASPSP where it is referenced.

### ISSUE THREAD

**Issue by henrikwidlund** [openpaymentseurope/docs#9]
There are references to sandbox data (PSU Ids) from ESSESESS in multiple files (ASPSP specific documentation for example). This should be removed from the documentation for other ASPSPs and clarified that it is specific to a certain ASPSP where it is referenced.

_Originally posted by @henrikwidlund in https://github.com/openpaymentseurope/docs/pull/7#issuecomment-564727936_

**Comment by janeklof** [comment]
Was due to work in progress on the ASPSP specific pages, should be cleaned up now.
